spring.application.name=FinalProject


# Connectionspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/demo_ds
spring.datasource.username=root
spring.datasource.password=

# Schema generation
spring.jpa.hibernate.ddl-auto=update

# Hibernate extras
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

yahoo.finance.base-url=https://query1.finance.yahoo.com
#
## 日志配置
#logging.level.com.hsbc.finalproject.service.Impl.TransactionServiceImpl=INFO
logging.level.root=INFO;
#logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
